seed : 42
sparsity_coeff : 4
reg_coeff : 0.001
num_epochs : 5
ckpt_iter : 10
ckpt_path : checkpoints
log_path : logs
duts3r_ckpt_path : duts3r_checkpoint
train_dataset: 
batch_size : 8
num_workers : 10